### PR TITLE
Capitalize United States (states -> States) and Airport

### PR DESCRIPTION
**Pull request by Nathansbud**

### CODE REVIEW

**Comment by dkotschessa** [comment]
@Nathansbud Sorry this took so incredibly long. I have not given this much attention!

**Review by dkotschessa — APPROVED** [review]

**Review by dkotschessa — APPROVED** [review]

**Comment by skarzi** [comment]
hi 👋 
@dkotschessa thanks for creating this useful faker provided! 
When do you plan to merge this PR and release a new version of the package?

**Comment by dkotschessa** [comment]
Thank you for the reminder! I had started it but gotten behind.  If I get
ahead on "real" work today I will try to catch up, otherwise sometime next
week.

**Comment by skarzi** [comment]
@dkotschessa kind reminder! If you need any help with the release etc. let me know I will try to help

**Pull request merged**
